#!/usr/bin/env bash
# spawn-temp.sh — create an ephemeral burst VM, run a command on it, and
# destroy it on exit (success or failure).
#
# Use this when you genuinely need two independent heavy Julia jobs running
# in parallel. For one heavy job at a time, use ~/bin/burst-run-heavy on the
# permanent fiber-raman-burst VM.
#
# Usage (from claude-code-host):
#   ~/bin/burst-spawn-temp <session-tag> <command>
#
# Example:
#   ~/bin/burst-spawn-temp B-parallel-sweep \
#       'julia -t auto --project=. scripts/my_other_sweep.jl'
#
# What it does:
#   1. If no recent machine-image of fiber-raman-burst exists (<48 h old),
#      creates one. Takes ~2 min the first time; near-instant on reuse.
#   2. Creates a new VM named fiber-raman-temp-<tag>-<timestamp> from the
#      machine image. Takes ~1 min.
#   3. SSHes in and runs the command directly (the new VM already has the
#      whole filesystem, Julia, git, and ~/bin scripts because it was
#      imaged from the working burst VM).
#   4. On exit (success, failure, or Ctrl-C), destroys the VM via a trap.
#      Also schedules a 6-hour auto-shutdown on the VM itself as a safety
#      net in case claude-code-host loses connection.
#
# COST NOTE: the ephemeral VM bills at ~$0.90/hr while running. The trap
# handler is the primary cleanup; the 6-hour auto-shutdown is backup.

set -euo pipefail

# ─── config ──────────────────────────────────────────────────────────────

PROJECT="${BURST_PROJECT:-riveralab}"
ZONE="${BURST_ZONE:-us-east5-a}"
SOURCE_VM="${BURST_SOURCE_VM:-fiber-raman-burst}"
MACHINE_IMAGE="${BURST_MACHINE_IMAGE:-fiber-raman-burst-template}"
MACHINE_TYPE="${BURST_MACHINE_TYPE:-c3-highcpu-22}"
IMAGE_MAX_AGE_HOURS="${BURST_IMAGE_MAX_AGE_HOURS:-48}"
AUTO_SHUTDOWN_HOURS="${BURST_AUTO_SHUTDOWN_HOURS:-6}"

# ─── args ────────────────────────────────────────────────────────────────

if [[ $# -lt 2 ]]; then
    cat <<USAGE >&2
usage: $(basename "$0") <session-tag> <command>

session-tag must match ^[A-Za-z]-[A-Za-z0-9_-]+$
command is executed on the ephemeral VM inside the repo directory.

env overrides: BURST_MACHINE_TYPE (default $MACHINE_TYPE),
               BURST_AUTO_SHUTDOWN_HOURS (default $AUTO_SHUTDOWN_HOURS).
USAGE
    exit 2
fi

SESSION="$1"; shift
CMD="$*"

if [[ ! "$SESSION" =~ ^[A-Za-z]-[A-Za-z0-9_-]+$ ]]; then
    echo "ERROR: session tag '$SESSION' must match <Letter>-<name>" >&2
    exit 2
fi

TIMESTAMP=$(date -u +%Y%m%dt%H%M%Sz)
VM_NAME="fiber-raman-temp-${SESSION,,}-${TIMESTAMP}"   # GCE requires lowercase
# Clamp name to 63 chars (GCE limit)
VM_NAME="${VM_NAME:0:63}"

log() { echo "[$(date -u +%H:%M:%SZ)] $*" >&2 ; }

# ─── step 1: ensure a fresh machine image exists ─────────────────────────

image_age_hours() {
    local ts
    ts=$(gcloud compute machine-images describe "$MACHINE_IMAGE" \
            --project="$PROJECT" \
            --format="value(creationTimestamp)" 2>/dev/null || true)
    [[ -z "$ts" ]] && { echo 999999; return; }
    local created_epoch
    created_epoch=$(date -d "$ts" +%s)
    local now_epoch; now_epoch=$(date +%s)
    echo $(( (now_epoch - created_epoch) / 3600 ))
}

ensure_machine_image() {
    local age
    age=$(image_age_hours)
    if (( age < IMAGE_MAX_AGE_HOURS )); then
        log "reusing machine image '$MACHINE_IMAGE' (age: ${age}h)"
        return 0
    fi

    if (( age < 999999 )); then
        log "machine image '$MACHINE_IMAGE' is ${age}h old (> ${IMAGE_MAX_AGE_HOURS}h); refreshing"
        gcloud compute machine-images delete "$MACHINE_IMAGE" \
            --project="$PROJECT" --quiet >/dev/null 2>&1 || true
    else
        log "no machine image '$MACHINE_IMAGE' exists; creating from $SOURCE_VM"
    fi

    log "creating machine image from $SOURCE_VM (this takes ~2 min)..."
    gcloud compute machine-images create "$MACHINE_IMAGE" \
        --source-instance="$SOURCE_VM" \
        --source-instance-zone="$ZONE" \
        --project="$PROJECT" \
        --description="Auto-generated by burst-spawn-temp. Safe to delete; will be recreated on next use." \
        >/dev/null
    log "machine image ready"
}

# ─── step 2: create the ephemeral VM ─────────────────────────────────────

create_vm() {
    log "creating ephemeral VM: $VM_NAME ($MACHINE_TYPE)"
    local create_out
    if ! create_out=$(gcloud compute instances create "$VM_NAME" \
        --source-machine-image="$MACHINE_IMAGE" \
        --machine-type="$MACHINE_TYPE" \
        --zone="$ZONE" \
        --project="$PROJECT" \
        --labels="purpose=ephemeral,session-tag=${SESSION,,},spawned-by=burst-spawn-temp" \
        2>&1); then
        echo "$create_out" >&2
        # Friendly diagnostics for the common quota failure
        if echo "$create_out" | grep -q "C3_CPUS" && echo "$create_out" | grep -q "Quota.*exceeded"; then
            cat >&2 <<HINT

────────────────────────────────────────────────────────────────────────
HINT: C3_CPUS regional quota is exhausted.

The machine image was built from a c3-highcpu-22 source, and GCE machine
images are locked to compatible (NVMe-capable) families. Our only
practical options are c3 or c3d, both of which use the C3_CPUS regional
quota. The main burst VM (fiber-raman-burst, c3-highcpu-22) already
consumes 22 vCPUs against the default 24-vCPU quota, so ephemerals
cannot fit.

To fix:

  1. Open https://console.cloud.google.com/iam-admin/quotas
     Project: riveralab · Region: us-east5 · Metric: "C3 CPUs"

  2. Request an increase to 64 or 96 (typical approval time: a few
     hours). Requesting 96 gives plenty of headroom for the main VM
     plus ~3 concurrent ephemerals.

  3. Once approved, re-run burst-spawn-temp unchanged.

Alternative (not recommended): downsize the main burst VM to
c3-highcpu-4 or -8 so ephemerals fit inside the existing 24-vCPU
ceiling. This trades main-VM throughput for spawn capacity.
────────────────────────────────────────────────────────────────────────
HINT
        fi
        return 1
    fi
    log "VM created; waiting for SSH..."

    local tries=0
    while (( tries < 30 )); do
        if gcloud compute ssh "$VM_NAME" \
            --zone="$ZONE" --project="$PROJECT" \
            --command='true' \
            --ssh-flag='-o ConnectTimeout=10' \
            --ssh-flag='-o StrictHostKeyChecking=no' \
            >/dev/null 2>&1; then
            log "SSH ready"
            return 0
        fi
        tries=$((tries + 1))
        sleep 10
    done
    log "ERROR: SSH did not become available in 5 min"
    return 1
}

destroy_vm() {
    log "destroying $VM_NAME"
    gcloud compute instances delete "$VM_NAME" \
        --zone="$ZONE" --project="$PROJECT" --quiet \
        >/dev/null 2>&1 || log "WARN: destroy failed (may already be gone)"
}

trap destroy_vm EXIT INT TERM

# ─── step 3: run the command ─────────────────────────────────────────────

run_remote() {
    log "running on $VM_NAME: $CMD"

    # Safety-net auto-shutdown in case claude-code-host loses connection
    # before our trap can fire. "sudo shutdown -h" runs in the background;
    # the trap destroy above is the normal cleanup path.
    gcloud compute ssh "$VM_NAME" \
        --zone="$ZONE" --project="$PROJECT" \
        --command="sudo shutdown -h +$((AUTO_SHUTDOWN_HOURS * 60))" \
        >/dev/null 2>&1 || true

    # Pull latest from main so the ephemeral VM has the newest code
    gcloud compute ssh "$VM_NAME" \
        --zone="$ZONE" --project="$PROJECT" \
        --command='cd fiber-raman-suppression && git fetch origin --quiet && git checkout main && git pull --ff-only origin main' \
        >/dev/null 2>&1 || log "WARN: git pull on ephemeral VM failed (continuing)"

    # Run the user's command via burst-run-heavy so the lock + per-run log
    # conventions still apply inside the ephemeral VM.
    gcloud compute ssh "$VM_NAME" \
        --zone="$ZONE" --project="$PROJECT" \
        --command="cd fiber-raman-suppression && \
                   export PATH=\$HOME/.juliaup/bin:\$HOME/bin:\$PATH && \
                   ~/bin/burst-run-heavy $SESSION '$CMD'"
}

# ─── main ────────────────────────────────────────────────────────────────

ensure_machine_image
create_vm
run_remote

log "job on $VM_NAME finished; trap will now destroy it"
