"""Notebook-friendly helpers for the fiber research engine.

This package is intentionally thin. It delegates to the maintained Julia CLI
entry points so notebooks do not become a second implementation of validation,
solver dispatch, or artifact contracts.
"""

from .cli import (
    CommandResult,
    artifact_plan,
    compute_plan,
    control_layout,
    dry_run_amp_on_phase_refinement,
    capabilities,
    dry_run_experiment,
    dry_run_sweep,
    explore_compare,
    explore_list,
    explore_plan,
    explore_run,
    execute_sweep,
    index_results,
    index_results_csv,
    lab_ready_config,
    lab_ready_latest,
    lab_ready_run,
    latest_experiment,
    latest_sweep,
    list_experiments,
    list_sweeps,
    objectives,
    refine_amp_on_phase,
    run_experiment,
    run_julia_cli,
    scaffold_objective,
    scaffold_variable,
    validate_all_experiments,
    validate_all_sweeps,
    validate_objective_extensions,
    validate_variable_extensions,
    variables,
)

__all__ = [
    "CommandResult",
    "artifact_plan",
    "capabilities",
    "compute_plan",
    "control_layout",
    "dry_run_amp_on_phase_refinement",
    "dry_run_experiment",
    "dry_run_sweep",
    "explore_compare",
    "explore_list",
    "explore_plan",
    "explore_run",
    "execute_sweep",
    "index_results",
    "index_results_csv",
    "lab_ready_config",
    "lab_ready_latest",
    "lab_ready_run",
    "latest_experiment",
    "latest_sweep",
    "list_experiments",
    "list_sweeps",
    "objectives",
    "refine_amp_on_phase",
    "run_experiment",
    "run_julia_cli",
    "scaffold_objective",
    "scaffold_variable",
    "validate_all_experiments",
    "validate_all_sweeps",
    "validate_objective_extensions",
    "validate_variable_extensions",
    "variables",
]
