"""
Phase 16 result analyzer — reads the JLD2 outputs from `mmf_run_phase16_all.jl`
and produces:
  - comparison bar chart: M=6 vs M=1 J_opt_dB per seed
  - convergence overlay: M=6 and M=1 J_history
  - mean-improvement summary table printed to stdout
  - results/raman/phase16/phase16_comparison.md markdown with the tables
  - results/raman/phase16/phase16_comparison.png combined figure

No numerical simulation required — pure post-processing of saved JLD2.
Safe to run on claude-code-host.
"""

ENV["MPLBACKEND"] = "Agg"

using Printf
using JLD2
using Statistics
using PyPlot

const RESULTS_DIR = joinpath(@__DIR__, "..", "results", "raman", "phase16")

struct RunStats
    seed::Int
    J_ref_dB::Float64
    J_opt_dB::Float64
    improvement_dB::Float64
    wall::Float64
end

function _load_mmf(seed::Int)
    fname = joinpath(RESULTS_DIR, @sprintf("baseline_M6_seed%d.jld2", seed))
    isfile(fname) || return nothing
    jldopen(fname, "r") do f
        RunStats(
            seed,
            f["J_ref_dB"],
            f["J_final_lin_dB"],
            f["improvement_dB"],
            f["wall_time"],
        )
    end
end

function _load_m1(seed::Int)
    fname = joinpath(RESULTS_DIR, @sprintf("baseline_M1_reference_seed%d.jld2", seed))
    isfile(fname) || return nothing
    jldopen(fname, "r") do f
        RunStats(
            seed,
            f["J_ref_dB"],
            f["J_lin_dB"],
            f["J_ref_dB"] - f["J_lin_dB"],
            f["wall"],
        )
    end
end

function _load_phi_traces(seed::Int)
    mmf_f = joinpath(RESULTS_DIR, @sprintf("baseline_M6_seed%d.jld2", seed))
    m1_f  = joinpath(RESULTS_DIR, @sprintf("baseline_M1_reference_seed%d.jld2", seed))
    mmf_trace = isfile(mmf_f) ? jldopen(mmf_f, "r")["J_history"] : Float64[]
    m1_trace  = isfile(m1_f)  ? jldopen(m1_f, "r")["J_trace"]   : Float64[]
    return mmf_trace, m1_trace
end

function analyze(; seeds = [42, 123, 7])
    @info "Phase 16 analyzer — reading from $RESULTS_DIR"

    mmf = filter(!isnothing, [_load_mmf(s) for s in seeds])
    m1  = filter(!isnothing, [_load_m1(s)  for s in seeds])

    isempty(mmf) && (@warn "No M=6 results found — is the runner still in progress?"; return)
    isempty(m1)  && (@warn "No M=1 results found — is the runner still in progress?"; return)

    @info "=" ^ 60
    @info "Phase 16 Summary"
    @info "=" ^ 60

    # Text tables
    @info @sprintf("%-8s %-12s %-12s %-12s %-10s", "seed", "J_ref[dB]", "J_opt[dB]", "Δ[dB]", "wall[s]")
    @info "-" ^ 60
    for r in mmf
        @info @sprintf("M6  %-6d %-12.2f %-12.2f %-12.2f %-10.1f",
            r.seed, r.J_ref_dB, r.J_opt_dB, r.improvement_dB, r.wall)
    end
    @info "-" ^ 60
    for r in m1
        @info @sprintf("M1  %-6d %-12.2f %-12.2f %-12.2f %-10.1f",
            r.seed, r.J_ref_dB, r.J_opt_dB, r.improvement_dB, r.wall)
    end

    mmf_mean_impr = mean([r.improvement_dB for r in mmf])
    m1_mean_impr  = mean([r.improvement_dB for r in m1])
    mmf_mean_J    = mean([r.J_opt_dB for r in mmf])
    m1_mean_J     = mean([r.J_opt_dB for r in m1])
    @info "-" ^ 60
    @info @sprintf("MEAN  M=6: J_opt=%.2f dB, Δ=%.2f dB ; M=1: J_opt=%.2f dB, Δ=%.2f dB",
        mmf_mean_J, mmf_mean_impr, m1_mean_J, m1_mean_impr)
    @info @sprintf("M=6 Δ vs M=1 Δ: %+.2f dB  (positive → M=6 shaper delivers more absolute suppression)",
        mmf_mean_impr - m1_mean_impr)
    @info @sprintf("M=6 J_opt vs M=1 J_opt: %+.2f dB  (positive → M=6 still has more residual Raman)",
        mmf_mean_J - m1_mean_J)

    # Markdown summary
    md_fname = joinpath(RESULTS_DIR, "phase16_comparison.md")
    open(md_fname, "w") do f
        println(f, "# Phase 16 Baseline — M=6 vs M=1 Comparison")
        println(f)
        println(f, "Auto-generated by `scripts/mmf_analyze_phase16.jl` from per-seed JLD2 files in `results/raman/phase16/`.")
        println(f)
        println(f, "## M=6 (GRIN-50, 6 modes, shared-across-modes spectral phase)")
        println(f)
        println(f, "| seed | J_ref [dB] | J_opt [dB] | ΔdB | wall [s] |")
        println(f, "|------|------------|------------|-----|----------|")
        for r in mmf
            println(f, @sprintf("| %d | %.2f | %.2f | %.2f | %.1f |",
                r.seed, r.J_ref_dB, r.J_opt_dB, r.improvement_dB, r.wall))
        end
        println(f)
        println(f, "## M=1 reference (SMF28_beta2_only)")
        println(f)
        println(f, "| seed | J_ref [dB] | J_opt [dB] | ΔdB | wall [s] |")
        println(f, "|------|------------|------------|-----|----------|")
        for r in m1
            println(f, @sprintf("| %d | %.2f | %.2f | %.2f | %.1f |",
                r.seed, r.J_ref_dB, r.J_opt_dB, r.improvement_dB, r.wall))
        end
        println(f)
        println(f, "## Aggregate")
        println(f)
        println(f, @sprintf("- M=6 mean Δ: **%.2f dB** (J_opt mean = %.2f dB)", mmf_mean_impr, mmf_mean_J))
        println(f, @sprintf("- M=1 mean Δ: **%.2f dB** (J_opt mean = %.2f dB)", m1_mean_impr, m1_mean_J))
        println(f, @sprintf("- M=6 Δ − M=1 Δ: **%+.2f dB**", mmf_mean_impr - m1_mean_impr))
        println(f, @sprintf("- M=6 J_opt − M=1 J_opt: **%+.2f dB**", mmf_mean_J - m1_mean_J))
    end
    @info "Saved $md_fname"

    # Figures
    seeds_common = sort(intersect([r.seed for r in mmf], [r.seed for r in m1]))

    # Bar chart
    fig, ax = subplots(figsize = (7, 4.5))
    x = collect(1:length(seeds_common))
    w = 0.35
    bars_m6 = [mmf[findfirst(r -> r.seed == s, mmf)].improvement_dB for s in seeds_common]
    bars_m1 = [m1[findfirst(r -> r.seed == s, m1)].improvement_dB   for s in seeds_common]
    ax.bar(x .- w/2, bars_m6, w, label = "M=6 (GRIN-50)", color = "C0")
    ax.bar(x .+ w/2, bars_m1, w, label = "M=1 (SMF28)",   color = "C3")
    ax.set_xticks(x)
    ax.set_xticklabels([string(s) for s in seeds_common])
    ax.set_xlabel("seed")
    ax.set_ylabel("ΔJ [dB] (higher = more Raman suppression)")
    ax.set_title("Phase 16 — M=6 vs M=1 improvement per seed")
    ax.grid(true, axis = "y", alpha = 0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(joinpath(RESULTS_DIR, "phase16_improvement_bar.png"), dpi = 300)
    close(fig)
    @info "Saved phase16_improvement_bar.png"

    # Convergence overlay
    fig, ax = subplots(figsize = (8, 4.5))
    for s in seeds_common
        mmf_tr, m1_tr = _load_phi_traces(s)
        if !isempty(mmf_tr)
            ax.plot(1:length(mmf_tr), mmf_tr, lw = 1.2, label = "M=6 seed=$s")
        end
        if !isempty(m1_tr)
            ax.plot(1:length(m1_tr), m1_tr, lw = 1.0, linestyle = "--", alpha = 0.7,
                label = "M=1 seed=$s")
        end
    end
    ax.set_xlabel("L-BFGS iteration")
    ax.set_ylabel("J_cost (log_cost=true, so in dB)")
    ax.set_title("Convergence traces — M=6 solid, M=1 dashed")
    ax.legend(fontsize = 8, ncol = 2)
    ax.grid(true, alpha = 0.3)
    fig.tight_layout()
    fig.savefig(joinpath(RESULTS_DIR, "phase16_convergence_overlay.png"), dpi = 300)
    close(fig)
    @info "Saved phase16_convergence_overlay.png"

    return (; mmf, m1, mmf_mean_impr, m1_mean_impr, mmf_mean_J, m1_mean_J)
end

if abspath(PROGRAM_FILE) == @__FILE__
    analyze()
end
